# Generated by Django 3.2.17 on 2023-07-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0013_alter_student_stdnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecords',
            fields=[
                ('expenseid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Expense ID')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Expense category')),
                ('amountrequired', models.CharField(blank=True, max_length=20, verbose_name='Amount required')),
                ('expensedate', models.DateField(verbose_name='Date of Expense')),
                ('amountpaid', models.CharField(blank=True, max_length=20, verbose_name='Amount paid')),
                ('balance', models.CharField(blank=True, max_length=20, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('paymentid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Pyament ID')),
                ('stdname', models.CharField(blank=True, max_length=255, verbose_name='Student name')),
                ('studentclass', models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], max_length=6, verbose_name='Class')),
                ('amount', models.CharField(blank=True, max_length=20, verbose_name='Amount paid')),
                ('balance', models.CharField(blank=True, max_length=20, verbose_name='Balance')),
                ('modeofpayment', models.CharField(blank=True, max_length=255, verbose_name='Mode of Payment')),
                ('date', models.DateField(verbose_name='Date of Payment')),
                ('stdnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.student', verbose_name='Student ID')),
            ],
        ),
    ]
