# Generated by Django 4.2.3 on 2023-07-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0015_alter_subjects_classlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.TextField(blank=True, max_length=25, verbose_name='Staff Name')),
                ('datepaid', models.DateField(blank=True, verbose_name='Payment Date')),
                ('salary', models.IntegerField(blank=True, verbose_name='Salary')),
                ('amountpaid', models.IntegerField(blank=True, verbose_name='Amount Paid')),
                ('balance', models.IntegerField(blank=True, verbose_name='Balance')),
                ('position', models.TextField(blank=True, max_length=15, verbose_name='Position')),
                ('bankaccnum', models.IntegerField(blank=True, max_length=30, verbose_name='Account Number')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.teachers')),
            ],
        ),
    ]
