# Generated by Django 4.2.2 on 2023-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
