# Generated by Django 4.2.2 on 2023-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='accumulatedpayment',
            field=models.IntegerField(default=None, verbose_name='Accumulated Amount'),
        ),
    ]
