# Generated by Django 4.2.7 on 2023-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='balance',
            field=models.IntegerField(blank=True, verbose_name='Balance'),
        ),
    ]
