# Generated by Django 4.2.2 on 2023-08-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaffpayment',
            name='bankaccnum',
        ),
        migrations.RemoveField(
            model_name='supportstaffpayment',
            name='paymentmethod',
        ),
    ]
