# Generated by Django 4.2.3 on 2023-08-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaffpayment',
            name='paymentdate',
            field=models.DateField(max_length=6, null=True, verbose_name='PAyment Date'),
        ),
    ]
