# Generated by Django 4.2.2 on 2023-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feesstructure',
            fields=[
                ('feesstructureid', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
