# Generated by Django 4.2.3 on 2023-07-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_subjects_classlevel'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(blank=True, max_length=20, verbose_name='Staff Names')),
                ('bankname', models.CharField(blank=True, max_length=30, verbose_name='Bank Name')),
                ('accnum', models.IntegerField(blank=True, verbose_name='Account Number')),
                ('accname', models.CharField(blank=True, max_length=25, verbose_name='Account Name')),
            ],
        ),
        migrations.AlterField(
            model_name='staffpayments',
            name='bankaccnum',
            field=models.IntegerField(blank=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='staffpayments',
            name='position',
            field=models.CharField(blank=True, max_length=15, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staffpayments',
            name='staffname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Staff Name'),
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('receiptnum', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='Receipt Number')),
                ('transactiondate', models.DateField(blank=True, verbose_name='Transaction Date')),
                ('amountpaid', models.IntegerField(blank=True, verbose_name='Amount Paid')),
                ('item', models.CharField(blank=True, max_length=30, verbose_name='Item')),
                ('balance', models.IntegerField(blank=True, verbose_name='Balance')),
                ('payername', models.CharField(blank=True, max_length=30, verbose_name='Payer Name')),
                ('receipts_staff_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.teachers')),
                ('recipts_staffpayments_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.staffpayments')),
            ],
        ),
    ]
