# Generated by Django 3.2.17 on 2023-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseRecords',
            new_name='ExpenseRecord',
        ),
    ]
