# Generated by Django 4.2.2 on 2023-09-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='fees',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='fees',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='term',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='year',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='receipts',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='staffpayments',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='staffpayments',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='supportstaffpayment',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='supportstaffpayment',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='teacherspayment',
            name='term',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='teacherspayment',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='Year'),
        ),
    ]
