# Generated by Django 4.2.3 on 2023-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherspayment',
            name='accumulatedpayment',
            field=models.IntegerField(default=None, verbose_name='Accumulated Amount'),
        ),
    ]
