# Generated by Django 4.2.2 on 2023-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaffpayment',
            name='supportstaffid',
            field=models.CharField(max_length=10, verbose_name='Support Staff id'),
        ),
    ]
