# Generated by Django 4.2.3 on 2023-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherspayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=25, verbose_name='Payment id')),
                ('paymentdate', models.DateField(verbose_name='Payment Date')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('amountpaid', models.IntegerField(verbose_name='Amount Paid')),
                ('balance', models.IntegerField(verbose_name='Balance')),
                ('paymentmethod', models.CharField(max_length=25, verbose_name='Payment Method')),
                ('bankaccnum', models.CharField(max_length=25, verbose_name='bankaccnum')),
            ],
        ),
    ]
