# Generated by Django 4.2.3 on 2023-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_supportstaffpayment_paymentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaffpayment',
            name='staffname',
            field=models.CharField(max_length=25, null=True, verbose_name='Staffname'),
        ),
    ]
