# Generated by Django 4.2.2 on 2023-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feesstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesstructure',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
