# Generated by Django 4.2.2 on 2023-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fees_accumulatedpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='accumulatedpayment',
            field=models.IntegerField(default=0),
        ),
    ]
