# Generated by Django 4.2.3 on 2023-08-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_schoolclasses_subjects_student_studentclass_and_more'),
        ('finance', '0002_teacherspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherspayment',
            name='teacherid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.teachers'),
        ),
    ]
