# Generated by Django 4.2.2 on 2023-08-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_teachers_bankaccnum_teachers_salary'),
        ('finance', '0002_remove_supportstaffpayment_bankaccnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaffpayment',
            name='supportstaffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.supportstaff'),
        ),
    ]
