# Generated by Django 4.2.3 on 2023-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_teacherspayment_accumulatedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaffpayment',
            name='accumulatedamount',
            field=models.IntegerField(default=None, verbose_name='Accumulated Amount'),
        ),
    ]
