# Generated by Django 4.2.7 on 2023-12-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_fees_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplementaryincome',
            fields=[
                ('supplementaryincomeid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Category')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.CharField(blank=True, max_length=20, verbose_name='Amount')),
                ('term', models.CharField(blank=True, default=None, max_length=10, verbose_name='Term')),
                ('year', models.PositiveIntegerField(blank=True, default=None, verbose_name='Year')),
            ],
        ),
    ]
