# Generated by Django 4.2.2 on 2023-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_fees_timestamp_alter_fees_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
