# Generated by Django 4.2.2 on 2023-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_supportstaffpayment_supportstaffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='classfees',
            field=models.CharField(blank=True, max_length=20, verbose_name='Class Fees'),
        ),
    ]
