# Generated by Django 4.2.2 on 2023-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_fees_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Year'),
        ),
    ]
