# Generated by Django 4.2.2 on 2023-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_fees_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('utilitiesid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Utility category')),
                ('utilitiesdate', models.DateField(verbose_name='Date of Utilities')),
                ('amountpaid', models.CharField(blank=True, max_length=20, verbose_name='Amount paid')),
                ('term', models.CharField(blank=True, default=None, max_length=10, verbose_name='Term')),
                ('year', models.PositiveIntegerField(blank=True, default=None, verbose_name='Year')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenseRecord',
        ),
    ]
