# Generated by Django 4.2.3 on 2023-08-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_schoolclasses_subjects_student_studentclass_and_more'),
        ('finance', '0003_teacherspayment_teacherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supportstaffpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=25, verbose_name='Payment id')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('amountpaid', models.IntegerField(verbose_name='Amount Paid')),
                ('balance', models.IntegerField(verbose_name='Balance')),
                ('paymentmethod', models.CharField(max_length=25, verbose_name='Payment Method')),
                ('bankaccnum', models.CharField(max_length=25, verbose_name='bankaccnum')),
                ('supportataffid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.supportstaff')),
            ],
        ),
    ]
