# Generated by Django 3.1.8 on 2024-09-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_supplementaryincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffpayments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
