# Generated by Django 4.2.3 on 2023-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_supportstaffpayment_supportstaffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpayments',
            name='bankaccnum',
            field=models.IntegerField(blank=True, default=None, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='teacherspayment',
            name='bankaccnum',
            field=models.CharField(default=None, max_length=25, verbose_name='bankaccnum'),
        ),
    ]
