# Generated by Django 4.2.2 on 2023-08-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expenserecord_expenseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='studentclass',
            field=models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], max_length=20, verbose_name='Class'),
        ),
    ]
