# Generated by Django 4.2.3 on 2023-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_supportstaffpayment_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherspayment',
            name='teachername',
            field=models.CharField(default=None, max_length=30, verbose_name='Teacher Name'),
        ),
        migrations.AlterField(
            model_name='teacherspayment',
            name='teacherid',
            field=models.CharField(max_length=20, verbose_name='Teacher id'),
        ),
    ]
