# Generated by Django 4.2.3 on 2023-08-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_staffpayments_bankaccnum_and_more'),
        ('finance', '0004_fees_classfees'),
    ]

    operations = [
    ]
