# Generated by Django 4.2.2 on 2023-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fees_classfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecord',
            name='amountrequired',
        ),
        migrations.RemoveField(
            model_name='expenserecord',
            name='balance',
        ),
    ]
