# Generated by Django 4.2.3 on 2023-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_merge_20230822_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaffpayment',
            name='supportstaffid',
            field=models.CharField(max_length=10, verbose_name='Support Staff id'),
        ),
    ]
