# Generated by Django 4.2.2 on 2023-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_fees_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='paymentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
