# Generated by Django 4.2.3 on 2023-08-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_merge_20230822_0159'),
        ('finance', '0005_remove_expenserecord_amountrequired_and_more'),
    ]

    operations = [
    ]
