# Generated by Django 4.2.3 on 2023-08-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_supportstaffpayment_supportstaffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherspayment',
            name='bankaccnum',
        ),
        migrations.RemoveField(
            model_name='teacherspayment',
            name='paymentmethod',
        ),
    ]
