# Generated by Django 4.2.3 on 2023-07-17 11:11

from django.db import migrations, models
import django.db.models.deletion

# Generated by Django 4.2.3 on 2023-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                # ... fields for Registration model ...
            ],
        ),
        migrations.CreateModel(
            name='Schoolclasses',
            fields=[
                # ... fields for Schoolclasses model ...
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                # ... fields for Subjects model ...
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                # ... fields for Teachers model ...
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Enter the password')),
            ],
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='subjects',
            field=models.ManyToManyField(to='frontend.subjects'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='classrelationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.schoolclasses'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjectrelationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.subjects'),
        ),
    ]
