# Generated by Django 4.2.3 on 2023-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Enter the password')),
            ],
        ),
    ]
