# Generated by Django 4.2.3 on 2023-08-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='classlevel',
            field=models.CharField(max_length=25, verbose_name='Class Level'),
        ),
    ]
