# Generated by Django 4.2.3 on 2023-07-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='computer',
            field=models.IntegerField(blank=True, default=None, verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='eng',
            field=models.IntegerField(blank=True, verbose_name='Eng'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='math',
            field=models.IntegerField(blank=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='re',
            field=models.IntegerField(blank=True, default=None, verbose_name='Religious Education'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sci',
            field=models.IntegerField(blank=True, verbose_name='Sci'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sst',
            field=models.IntegerField(blank=True, verbose_name='SST'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='stdnum',
            field=models.ForeignKey(blank=True, default='std_000', on_delete=django.db.models.deletion.CASCADE, to='frontend.student'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='studentclass',
            field=models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], default='P.7', max_length=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='term',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=3, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='year',
            field=models.CharField(blank=True, default='2023', max_length=5, verbose_name='Year'),
        ),
    ]
