# Generated by Django 4.2.2 on 2023-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='supportstaff_profiles/'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Supportstaff id'),
        ),
    ]
