# Generated by Django 4.2.2 on 2023-08-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaff',
            name='password',
        ),
        migrations.RemoveField(
            model_name='supportstaff',
            name='username',
        ),
    ]
