# Generated by Django 4.2.5 on 2023-09-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=255, verbose_name='Password'),
        ),
    ]
