# Generated by Django 4.2.5 on 2023-11-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term', models.CharField(max_length=25, verbose_name='Current Term')),
                ('current_year', models.CharField(max_length=25, verbose_name='Current Year')),
                ('stdclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.schoolclasses')),
                ('stdnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.student')),
            ],
        ),
    ]
