# Generated by Django 4.2.3 on 2023-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=25, verbose_name='Username'),
        ),
    ]
