# Generated by Django 4.2.5 on 2023-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='current_term',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='mark',
            name='current_year',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
