# Generated by Django 4.2.3 on 2023-08-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_type',
            field=models.CharField(choices=[('Test', 'Test'), ('BOT', 'BOT Exams'), ('MOT', 'MOT Exams'), ('EOT', 'EOT Exams')], default=None, max_length=20),
        ),
    ]
