# Generated by Django 4.2.5 on 2023-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclasses',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='classlevel',
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='box_number',
            field=models.CharField(max_length=50, verbose_name='Box Number'),
        ),
    ]
