# Generated by Django 4.2.3 on 2023-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='class_level',
            field=models.CharField(default=None, max_length=20, verbose_name='Class Level'),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='classteacher',
            field=models.CharField(default=None, max_length=20, verbose_name='Class teacher'),
        ),
    ]
