# Generated by Django 4.2.3 on 2023-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasses',
            name='classteacher',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Class teacher'),
        ),
    ]
