# Generated by Django 4.2.3 on 2023-07-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='primaryonemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField(verbose_name='Math')),
                ('eng', models.IntegerField(verbose_name='Eng')),
                ('sci', models.IntegerField(verbose_name='Sci')),
                ('sst', models.IntegerField(verbose_name='SST')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stdnumber', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='Registration Number')),
                ('regdate', models.DateField(blank=True, default=None, verbose_name='Date')),
                ('childname', models.CharField(blank=True, max_length=25, verbose_name="Child's Name")),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name="Child's Gender")),
                ('dob', models.DateField(blank=True, default=None, verbose_name='Date of Birth')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='Address')),
                ('house', models.CharField(blank=True, max_length=20, verbose_name='House')),
                ('studentclass', models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], max_length=6, verbose_name='House')),
                ('fathername', models.CharField(blank=True, max_length=25, verbose_name="Father's Name")),
                ('fcontact', models.CharField(blank=True, max_length=10, verbose_name="Father's Contact")),
                ('foccupation', models.CharField(blank=True, max_length=20, verbose_name="Father's Occupation")),
                ('mothername', models.CharField(blank=True, max_length=25, verbose_name="Mother's Name")),
                ('mcontact', models.CharField(blank=True, max_length=10, verbose_name="Mother's Contact")),
                ('moccupation', models.CharField(blank=True, max_length=20, verbose_name="Mother's Occupation")),
                ('livingwith', models.CharField(blank=True, max_length=20, verbose_name='Living With')),
                ('guardianname', models.CharField(blank=True, max_length=10, verbose_name='Guardian Names')),
                ('gcontact', models.CharField(blank=True, max_length=10, verbose_name="Guardian's Contact")),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='classrelationship',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjectrelationship',
        ),
        migrations.AddField(
            model_name='primaryonemarks',
            name='stdnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.students'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='classrelationship',
            field=models.ManyToManyField(to='frontend.schoolclasses'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjectrelationship',
            field=models.ManyToManyField(to='frontend.subjects'),
        ),
    ]
