# Generated by Django 4.2.3 on 2023-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.TextField(verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='fathersemail',
            field=models.EmailField(max_length=30, verbose_name='Fathers email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mothersemail',
            field=models.EmailField(max_length=30, verbose_name='Mothers email'),
        ),
    ]
