# Generated by Django 3.2.17 on 2023-07-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='classes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Classes Taught'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='qualification',
            field=models.CharField(blank=True, max_length=20, verbose_name='Academic Qualifications'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(blank=True, max_length=20, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='Username'),
        ),
    ]
