# Generated by Django 4.2.2 on 2023-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_supportstaff_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=100, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='Username'),
        ),
    ]
