# Generated by Django 4.2.2 on 2023-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_supportstaff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
