# Generated by Django 4.2.5 on 2023-11-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_mark', models.CharField(max_length=10, verbose_name='Promotion Mark')),
            ],
        ),
    ]
