# Generated by Django 4.2.3 on 2023-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_login_email_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
    ]
