# Generated by Django 4.2.3 on 2023-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_schoolclasses_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='subjects',
            field=models.ManyToManyField(to='frontend.subjects'),
        ),
    ]
