# Generated by Django 4.2.3 on 2023-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_primaryonemarks_students_delete_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryonemarks',
            name='term',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=3, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stdnumber',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='Student Number'),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentclass',
            field=models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], max_length=6, verbose_name='Class'),
        ),
    ]
