# Generated by Django 4.2.3 on 2023-08-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_schoolclasses_subjects_student_studentclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='bankaccnum',
            field=models.CharField(default=None, max_length=100, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='salary',
            field=models.CharField(default=None, max_length=100, verbose_name='Salary'),
        ),
    ]
