# Generated by Django 4.2.3 on 2023-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term', models.CharField(max_length=25, verbose_name='Current Term')),
                ('current_year', models.CharField(max_length=25, verbose_name='Current Year')),
            ],
        ),
    ]
