# Generated by Django 4.2.3 on 2023-07-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_login_alter_registration_fathersemail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='motherwsresidence',
            new_name='mothersresidence',
        ),
    ]
