# Generated by Django 4.2.5 on 2023-09-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.schoolclasses')),
                ('subjects', models.ManyToManyField(to='frontend.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.teachers')),
            ],
        ),
    ]
