# Generated by Django 4.2.3 on 2023-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_registration_appliedclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='classrelationship',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjectrelationship',
        ),
        migrations.AddField(
            model_name='teachers',
            name='classrelationship',
            field=models.ManyToManyField(to='frontend.schoolclasses'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjectrelationship',
            field=models.ManyToManyField(to='frontend.subjects'),
        ),
    ]
