# Generated by Django 4.2.3 on 2023-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_marks_computer_alter_marks_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
