# Generated by Django 4.2.3 on 2023-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(default=None, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
