# Generated by Django 4.2.3 on 2023-08-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_schoolclasses_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentclass',
        ),
    ]
