# Generated by Django 4.2.3 on 2023-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_delete_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fathersphoto',
            field=models.ImageField(upload_to='imagesfile', verbose_name='Fathers passport photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='guardianphoto',
            field=models.ImageField(upload_to='imagesfile', verbose_name='Guardians Photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mothersphoto',
            field=models.ImageField(upload_to='imagesfile', verbose_name='Mothers passport photo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passportphoto',
            field=models.ImageField(upload_to='imagesfiles', verbose_name='Childs Passport photo'),
        ),
    ]
