# Generated by Django 4.2.3 on 2023-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_teachers_bankaccnum_teachers_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaff',
            name='fullname',
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='bankaccnum',
            field=models.CharField(default=None, max_length=100, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='joiningdate',
            field=models.DateField(default=None, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='password',
            field=models.CharField(default=None, max_length=100, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='salary',
            field=models.CharField(default=None, max_length=100, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.CharField(default=None, max_length=20, verbose_name='Support Stuff id'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='supportstaffnames',
            field=models.CharField(default=None, max_length=30, verbose_name='Suppot Staff Names'),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='address',
            field=models.CharField(default=None, max_length=20, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='contact',
            field=models.CharField(default=None, max_length=13, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='gender',
            field=models.CharField(default=None, max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='position',
            field=models.CharField(default=None, max_length=20, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='qualification',
            field=models.CharField(default=None, max_length=100, verbose_name='Academic Qualifications'),
        ),
    ]
