# Generated by Django 4.2.2 on 2023-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_supportstaff_supportstaffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='bankaccnum',
            field=models.CharField(default=None, max_length=100, verbose_name='Bank Account No.'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='salary',
            field=models.CharField(default=None, max_length=100, verbose_name='Salary'),
        ),
    ]
