# Generated by Django 4.2.3 on 2023-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_primaryonemarks_term_alter_students_stdnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryonemarks',
            name='year',
            field=models.CharField(default='2023', max_length=5, verbose_name='Year'),
        ),
    ]
