# Generated by Django 4.2.2 on 2023-09-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schoolpaycode',
            field=models.CharField(blank=True, max_length=10, verbose_name='School Pay Code'),
        ),
    ]
