# Generated by Django 4.2.3 on 2023-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username')),
                ('contact', models.CharField(max_length=20, verbose_name='Phone contact')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('dob', models.DateField(default=None, verbose_name='Date of Birth')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
