# Generated by Django 4.2.3 on 2023-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_term_end_date_term_start_date_term_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=150, verbose_name='School name')),
                ('badge', models.ImageField(blank=True, null=True, upload_to='school_badge/')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('box_number', models.CharField(max_length=15, verbose_name='Box Number')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
            ],
        ),
    ]
