# Generated by Django 4.2.3 on 2023-07-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username')),
                ('contact', models.CharField(max_length=20, verbose_name='Phone contact')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('dob', models.DateField(default=None, verbose_name='Date of Birth')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=255, verbose_name='Role Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='admin_model',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.role_model', verbose_name='Role'),
        ),
    ]
