# Generated by Django 4.2.3 on 2023-07-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_primaryonemarks_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='primaryonemarks',
            new_name='marks',
        ),
    ]
