# Generated by Django 4.2.3 on 2023-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_marks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='stdnum',
            field=models.CharField(blank=True, default='std_000', max_length=100, verbose_name='Stud number'),
        ),
    ]
