# Generated by Django 4.2.5 on 2023-10-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_student_schoolpaycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
