# Generated by Django 4.2.3 on 2023-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_teachers_bankaccnum_teachers_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, verbose_name='Ful Name')),
                ('gender', models.CharField(max_length=7, verbose_name='Gender')),
                ('address', models.CharField(max_length=15, verbose_name='Address')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('profileimage', models.ImageField(upload_to='', verbose_name='Profile Image')),
                ('role', models.CharField(max_length=10, verbose_name='Role')),
                ('qualification', models.CharField(max_length=30, verbose_name='Qualifications')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('bankaccnum', models.IntegerField(verbose_name='Bank Account Number')),
                ('username', models.CharField(max_length=20, verbose_name='User Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
