# Generated by Django 4.2.3 on 2023-08-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_supportstaff_fullname_supportstaff_bankaccnum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportstaff',
            name='id',
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='Support Stuff id'),
        ),
    ]
