# Generated by Django 4.2.3 on 2023-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_primaryonemarks_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='studentclass',
            field=models.CharField(choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], default='P.7', max_length=10),
        ),
    ]
