# Generated by Django 4.2.3 on 2023-08-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_supportstaff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Support Stuff id'),
        ),
    ]
