# Generated by Django 4.2.3 on 2023-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_admin_model_role_model_delete_admin_admin_model_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supportstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Full Name')),
                ('contact', models.CharField(max_length=20, verbose_name='Phone contact')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(default=None, verbose_name='Date of Birth')),
                ('qualification', models.CharField(blank=True, max_length=255, verbose_name='Qualification')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Position')),
            ],
        ),
        migrations.AddField(
            model_name='admin_model',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, verbose_name='Gender'),
        ),
    ]
