# Generated by Django 4.2.6 on 2023-11-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_promotion_promotion_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
