# Generated by Django 4.2.3 on 2023-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_marks_stdnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='classlevel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Class Level'),
        ),
    ]
