# Generated by Django 4.2.3 on 2023-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_marks_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='computer',
            field=models.IntegerField(default=None, verbose_name='Computer'),
        ),
        migrations.AddField(
            model_name='marks',
            name='re',
            field=models.IntegerField(default=None, verbose_name='Religious Education'),
        ),
    ]
