# Generated by Django 4.2.3 on 2023-08-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20230731_2228'),
        ('frontend', '0006_schoolclasses_classlevel'),
    ]

    operations = [
    ]
