# Generated by Django 4.2.3 on 2023-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_supportstaff_admin_model_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_model',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='Admin ID'),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone contact'),
        ),
    ]
