# Generated by Django 3.2.17 on 2023-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_admin_model_id_alter_supportstaff_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaff',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='Staff Number'),
        ),
    ]
