# Generated by Django 4.2.3 on 2023-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_merge_20230801_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclasses',
            name='classlevel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classlevel'),
        ),
    ]
