# Generated by Django 4.2.6 on 2023-11-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
