# Generated by Django 4.2.3 on 2023-07-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_marks_computer_marks_re'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='stdnum',
            field=models.ForeignKey(default='std_000', on_delete=django.db.models.deletion.CASCADE, to='frontend.students'),
        ),
    ]
