# Generated by Django 3.2.17 on 2023-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_supportstaff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
