# Generated by Django 4.2.3 on 2023-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_schoolclasses_classlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentclass',
            field=models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], default=None, max_length=10),
        ),
    ]
