# Generated by Django 4.2.3 on 2023-08-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_schoolclasses_classlevels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclasses',
            name='classlevels',
        ),
    ]
