# Generated by Django 4.2.3 on 2023-07-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_marks_stdnum'),
        ('frontend', '0010_auto_20230719_1424'),
    ]

    operations = [
    ]
