# Generated by Django 3.2.17 on 2023-07-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20230721_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
