# Generated by Django 4.2.3 on 2023-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_merge_0008_alter_marks_stdnum_0010_auto_20230719_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='classid',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='Class id'),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='classname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Class Name'),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='classteacher',
            field=models.CharField(blank=True, max_length=10, verbose_name='Classteacher'),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='numofstds',
            field=models.CharField(blank=True, max_length=4, verbose_name='Number of Students'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='classlevel',
            field=models.CharField(blank=True, max_length=25, verbose_name='Class Level'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjecthead',
            field=models.CharField(blank=True, max_length=25, verbose_name='Head of Subject'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjectid',
            field=models.CharField(default='subj_000', max_length=25, primary_key=True, serialize=False, verbose_name='Subject id'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjectname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Subject Name'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='address',
            field=models.CharField(blank=True, max_length=20, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='classes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Classes Taught'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='contact',
            field=models.CharField(blank=True, max_length=10, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='dob',
            field=models.DateField(blank=True, default=None, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='joiningdate',
            field=models.DateField(blank=True, default=None, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(blank=True, max_length=20, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='position',
            field=models.CharField(blank=True, max_length=20, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='qualification',
            field=models.CharField(blank=True, max_length=20, verbose_name='Academic Qualifications'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.CharField(blank=True, max_length=20, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacherid',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, verbose_name='Teacher id'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teachernames',
            field=models.CharField(blank=True, max_length=25, verbose_name='Teachers Names'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='username',
            field=models.CharField(blank=True, max_length=20, verbose_name='Username'),
        ),
    ]
