# Generated by Django 4.2.3 on 2023-08-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_teachers_address_alter_teachers_contact_and_more'),
        ('frontend', '0012_remove_schoolclasses_classlevel_and_more'),
    ]

    operations = [
    ]
