# Generated by Django 4.2.3 on 2023-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='classlevel',
            field=models.CharField(default=None, max_length=25, verbose_name='Class Level'),
        ),
    ]
