# Generated by Django 4.2.3 on 2023-08-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_merge_20230803_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclasses',
            old_name='classlevels',
            new_name='classlevel',
        ),
    ]
