# Generated by Django 4.2.3 on 2023-07-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_subjects_classlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='classlevel',
            field=models.CharField(max_length=25, verbose_name='Class Level'),
        ),
    ]
