# Generated by Django 3.2.17 on 2023-07-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_student_regdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentclass',
            new_name='stdclass',
        ),
    ]
