# Generated by Django 3.2.17 on 2023-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_rename_studentclass_student_stdclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.CharField(blank=True, choices=[('baby', 'baby'), ('middle', 'middle'), ('top', 'top'), ('P.1', 'P.1'), ('P.2', 'P.2'), ('P.3', 'P.3'), ('P.4', 'P.4'), ('P.5', 'P.5'), ('P.6', 'P.6'), ('P.7', 'P.7')], max_length=10, verbose_name='Class'),
        ),
    ]
