# Generated by Django 3.2.17 on 2023-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_alter_student_stdclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Class'),
        ),
    ]
