# Generated by Django 4.2.7 on 2023-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_supportstaff_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nin',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Nin'),
        ),
    ]
