# Generated by Django 3.2.17 on 2023-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_student_stdclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.CharField(blank=True, default=None, max_length=10, verbose_name='Class'),
        ),
    ]
