# Generated by Django 4.2.7 on 2023-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_remove_student_nin_student_lin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportstaff',
            name='supportstaffid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
